
#w przyszlosci dodam tutaj redisa
services:

  postgres:

    image: postgres:18

    container_name: betting-postgres

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2137

      - POSTGRES_DB=bettingDb

    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:7

    container_name: betting_redis

    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: betting_rabbitmq
    ports:
      - "5672:5672"   # Port AMQP do komunikacji dla aplikacji
      - "15672:15672" # Port HTTP dla panelu zarządzania w przeglądarce
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres-data:
    driver: local