
#w przyszlosci dodam tutaj redisa
services:

  postgres:

    image: postgres:18

    container_name: betting-postgres

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2137

      - POSTGRES_DB=bettingDb

    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:7

    container_name: betting_redis

    ports:
      - "6379:6379"

volumes:
  postgres-data:
    driver: local